### ISSUE TITLE
Close connection?

### ISSUE THREAD

**Issue by eddelbuettel** [r-lib/liteq#15]
When I am trying (simple enough) things in littler, things end on:

```sh
Warning message:
call dbDisconnect() when finished working with a connection
```

The queue object creator does not share the connection with me.  Should it?  Or should there be a disconnect helper?

**Comment by gaborcsardi** [comment]
Yeah, `DBI` / `RSQLite` used be silent about these, but the most recent version is not, so `liteq` should close connections explicitly...

**Comment by eddelbuettel** [comment]
I'd be happy to call it myself at end if exposed...

**Comment by gaborcsardi** [comment]
No, `liteq` should call it. THe warning is harmless, btw, but it is annoying....

**Comment by wlandau** [comment]
Seems like a simple matter of disconnecting from the message's lock in `ack()` and `nack()`. PR: #20.
