### ISSUE TITLE
Check if a queue is nonempty

### ISSUE THREAD

**Issue by wlandau** [r-lib/liteq#16]
I am thinking of a function faster than `list_messages()` that does not try to consume any messages.

**Comment by gaborcsardi** [comment]
You can just try to consume and then drop the consumed item.

**Comment by gaborcsardi** [comment]
Or probably even better to `nack()` it.

**Comment by gaborcsardi** [comment]
Btw. why would you check it, if you don't want to comsume?

**Comment by wlandau** [comment]
I suppose `try_consume(); nack()` might work, but I worry about race conditions.

1. master: `msg <- try_consume(q)`
1. worker: `msg <- consume(q)`
1. worker: process `msg`
1. worker: `ack(msg)`
1. master: `nack(msg)`

It seems like (5) would reference a message that no longer exists:

```r
Error in db_ack(message$db, message$queue, message$id, message$lock, FALSE) : 
  Message does not exist, internal error?
```

This sort of thing comes up in [`workers`](https://github.com/wlandau/workers), a multi-purpose scheduler I just started. The [`liteq` branch](https://github.com/wlandau/workers/tree/liteq) is not currently working, but I love having `liteq`! The immediate goal is the walk a DAG of jobs using persistent workers, and I have plans to extend it to a serious scheduler with proper load-balancing and semi-transient workers. All this supports [`drake`](https://github.com/ropensci/drake).

Does something like [`workers`](https://github.com/wlandau/workers) already exist? @krlmlr mentioned that you and/or @lionel- might be working on something similar. If that is the case, I will adjust my plans to avoid duplicating your work.

**Comment by gaborcsardi** [comment]
> master: msg <- try_consume(q)
> worker: msg <- consume(q)

Worker will not get `msg` if master already has it.

**Comment by wlandau** [comment]
In my case, that's also an obstacle.

**Comment by gaborcsardi** [comment]
Why would we schedule a job to a worker if another worker is already working on it?

**Comment by gaborcsardi** [comment]
Anyway, it is easy enough to write an `is_empty()` method if you want to submit a PR.  It is just like `list_message()` with a slightly different SQL query.

**Comment by wlandau** [comment]
Thanks!

In my case, the job gets scheduled to only one worker, and the master just checks if the worker has tasks assigned to it.
