### ISSUE TITLE
Package status?

### ISSUE THREAD

**Issue by tzakharko** [r-lib/liteq#23]
Just discovered this little gem of a package, but I see that the latest update is a while back. Is the package considered to be stable and feature-complete or was it dropped in favor of some other approach?

**Comment by gaborcsardi** [comment]
It is feature complete, and not abandoned. Bugs will be fixed. If you just need locking for concurrency, then you can also use the filelock package, that is simpler.

**Comment by tzakharko** [comment]
Thanks, that's good to know. My current use case is work synchronization across multiple R processes. I am however consistently getting "database is locked" errors, I will investigate and open a bug report if nessesary.

**Comment by gaborcsardi** [comment]
If you are locking for a long time, then you might need to increase the timeout of liteq. Set the `R_LITEQ_BUSY_TIEMOUT` environment variables, https://github.com/r-lib/liteq/blob/f7968687c63e1343503bf4c8828366222cfdbb58/NEWS.md#L4

**Comment by Enchufa2** [comment]
This may be related to #25, which is now fixed in the development version.
